### ISSUE TITLE
Error when searching for "p"

### ISSUE THREAD

**Issue by MalteWunsch** [Wuzzitor/metagist-server#3]
Searching for "p" via http://metagist.org/search?query=p a few minutes ago resulted in an error page asking me to open this issue :)

Packagist seemed to be up at that time.

**Comment by bonndan** [comment]
Thanks for reporting the bug. This issue will be addressed this weekend :)

Cause: Package name validator returns "The package name p is invalid.", but should not validate the name at this point.
